package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// exceptions:
//
// If a line begins with "%toc", it is replaced with a table of contents
// consisting of links to the top two levels of headers below the %toc symbol.
//
// If a line begins with "%include FILENAME TAG", it is replaced with the lines
// of the file between lines containing "!+TAG" and  "!-TAG". TAG can be omitted,
// in which case the entire file is included. Typically used to embed code samples.
//
// The relative path FILENAME is resolved from the markdown file location.
// For example, if the current markdown file is cmd/hello/README.md,
// and it uses %include, it looks for code.go relative to the cmd/hello/
// directory. If FILENAME contains no path separators,
// it is resolved relative to GOROOT/src.
//
// In the resulting output, all lines of included code are indented
// by a single tab, and leading tabs common to all non-blank lines
// are removed.
//
// Comments whose text is "//-" or "//+" are omitted entirely.
// Comments whose text is "// ^" are replaced by blank lines.

var output = flag.String("o", "", "output file name")

func main() {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("recovered from panic: %v", r)
			os.Exit(1)
		}
	}()
	
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "usage: weave [flags] <input.md>\n\nflags:\n")
		flag.PrintDefaults()
	}
	flag.Parse()
	if flag.NArg() != 1 {
		flag.Usage()
		os.Exit(2)
	}

	log.SetFlags(0)
	log.SetPrefix("weave: ")

	wd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	curDir := filepath.Base(wd)

	in, err := os.Open(flag.Arg(0))
	if err != nil {
		log.Fatal(err)
	}
	defer in.Close()

	out := os.Stdout
	if *output != "" {
		out, err = os.Create(*output)
		if err != nil {
			log.Fatal(err)
		}
		defer func() {
			if err := out.Close(); err != nil {
				log.Fatal(err)
			}
		}()
	}

	printf := func(format string, args ...any) {
		if _, err := fmt.Fprintf(out, format, args...); err != nil {
			log.Fatalf("writing failed: %v", err)
		}
	}

	printf("<!-- Autogenerated by weave; DO NOT EDIT -->\n")

	// Pass 1: extract table of contents.
	type tocEntry struct {
		depth  int
		text   string
		anchor string
	}
	var (
		toc []tocEntry
		// We indent toc items according to their header depth, so that nested
		// headers result in nested lists. However, we want the lowest header depth
		// to correspond to the root of the list. Otherwise, the entire list is
		// indented, which turns it into a code block rather than an outline.
		minTocDepth = 999 // Initialize to high value instead of 0
	)
	scanner := bufio.NewScanner(in)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || (line[0] != '#' && line[0] != '%') {
			continue
		}
		line = strings.TrimSpace(line)
		if line == "%toc" {
			toc = nil
			minTocDepth = 999 // Reset to high value
		} else if strings.HasPrefix(line, "# ") ||
			strings.HasPrefix(line, "## ") ||
			strings.HasPrefix(line, "### ") ||
			strings.HasPrefix(line, "#### ") {

			words := strings.Fields(line)
			if len(words) < 2 {
				continue // Skip malformed headers
			}
			depth := len(words[0])
			if depth < minTocDepth {
				minTocDepth = depth
			}
			words = words[1:]
			text := strings.Join(words, " ")
			if text == "" {
				continue // Skip empty headers
			}
			anchor := strings.Join(words, "-")
			anchor = strings.ToLower(anchor)
			anchor = strings.ReplaceAll(anchor, "**", "")
			anchor = strings.ReplaceAll(anchor, "`", "")
			anchor = strings.ReplaceAll(anchor, "_", "")
			toc = append(toc, tocEntry{depth: depth, text: text, anchor: anchor})
		}
	}
	if scanner.Err() != nil {
		log.Fatal(scanner.Err())
	}

	// Reset minTocDepth if no headers were found
	if minTocDepth == 999 {
		minTocDepth = 1
	}

	// Pass 2.
	if _, err := in.Seek(0, io.SeekStart); err != nil {
		log.Fatalf("can't rewind input: %v", err)
	}
	scanner = bufio.NewScanner(in)
	for scanner.Scan() {
		line := scanner.Text()
		switch {
		case strings.HasPrefix(line, "%toc"): // ToC
			for _, h := range toc {
				// Only print two levels of headings.
				if h.depth-minTocDepth <= 1 && h.text != "" && h.anchor != "" {
					printf("%s1. [%s](#%s)\n", strings.Repeat("\t", h.depth-minTocDepth), h.text, h.anchor)
				}
			}
		case strings.HasPrefix(line, "%include"):
			words := strings.Fields(line)
			var section string
			caption := true
			switch len(words) {
			case 2: // %include filename
			// Nothing to do.
			case 3: // %include filename section OR %include filename -
				if words[2] == "-" {
					caption = false
				} else {
					section = words[2]
				}
			case 4: // %include filename section -
				section = words[2]
				if words[3] != "-" {
					log.Fatalf("last word is not '-': %s", line)
				}
				caption = false
			default:
				log.Fatalf("wrong # words (want 2-4): %s", line)
			}
			filename := words[1]

			if caption {
				printf("\t// go get golang.org/x/example/%s/%s\n\n",
					curDir, filepath.Dir(filename))
			}

			s, err := include(filename, section)
			if err != nil {
				log.Fatal(err)
			}
			printf("```go\n")
			printf("%s\n", cleanListing(s)) // TODO(adonovan): escape /^```/ in s
			printf("```\n")
		default:
			printf("%s\n", line)
		}
	}
	if scanner.Err() != nil {
		log.Fatal(scanner.Err())
	}
}

// include returns the contents of the named file,
// restricted to the lines between markers.
//
// If tag=="", the entire file is returned.
// Otherwise, the result comprises the lines between
// the first line that matches "!+tag" and the first
// subsequent line that matches "!-tag".
// The matching lines are excluded.
//
// +tag and -tag are regular expressions.
// In practice, tags are alphanumeric,
// and the "!" becomes a line comment in the host language,
// so the tags are ignored when compiling.
// This is true even if tag=="".
func include(file, tag string) (string, error) {
	f, err := os.Open(file)
	if err != nil {
		return "", err
	}
	defer f.Close()

	startre, err := regexp.Compile("!\\+" + tag + "$")
	if err != nil {
		return "", err
	}
	endre, err := regexp.Compile("!\\-" + tag + "$")
	if err != nil {
		return "", err
	}

	var text bytes.Buffer
	in := bufio.NewScanner(f)
	var on bool
	for in.Scan() {
		line := in.Text()
		switch {
		case startre.MatchString(line):
			on = true
		case endre.MatchString(line):
			on = false
		case on:
			text.WriteByte('\t')
			text.WriteString(line)
			text.WriteByte('\n')
		}
	}
	if in.Err() != nil {
		return "", in.Err()
	}
	if text.Len() == 0 {
		return "", fmt.Errorf("no lines of %s matched tag %q", file, tag)
	}
	return text.String(), nil
}

// cleanListing returns the lines of text with the following edits:
//
// - comments of the form "//" + op are removed, where op is "+" or "-";
// - comments of the form "// ^" are replaced by blank lines;
// - a common prefix of tabs is removed from all non-blank lines;
// - blank lines at the start and end are removed.
//
// This allows us to include code samples that contain additional text,
// and remove n leading tabs.
func cleanListing(text string) string {
	lines := strings.Split(text, "\n")

	// remove minimum number of leading tabs from all non-blank lines
	tabs := 999
	for i, line := range lines {
		if strings.TrimSpace(line) == "" {
			lines[i] = ""
		} else {
			if n := leadingTabs(line); n < tabs {
				tabs = n
			}
		}
	}
	for i, line := range lines {
		if line != "" {
			line := line[tabs:]
			lines[i] = line // remove leading tabs
		}
	}

	// remove leading blank lines
	for len(lines) > 0 && lines[0] == "" {
		lines = lines[1:]
	}
	// remove trailing blank lines
	for len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	return strings.Join(lines, "\n")
}

func leadingTabs(s string) int {
	var i int
	for i = 0; i < len(s); i++ {
		if s[i] != '\t' {
			break
		}
	}
	return i
}
